### PR TITLE
Logs view revamp:

### PR DESCRIPTION
**Pull request by Bastiti**
- Download button is synced with main theme
- Logs are now in a scrollable Table.
- Scrollbar is revamp to be synced with main theme
- info.html had a bad class for FIRMWARE
- Added spaces for packet logging because of overlapping text in info.html
- TaskWeb now replace spaces with &nbsp; and format logs for being viewable and remove the last line.
- CSS was edited for being responsible with the type of screen.

- Test made in local.

### CODE REVIEW

**Comment by mdiepart** [comment]
I think the sanitize function should be restricted to sanitizing a string for HTML display. Inserting the table tags should be done outside this function.

I'm gonna work on that now

**Comment by mdiepart** [comment]
It would be nice not having to hardcode the table headers in the CSS file... Do you think there is another way of managing the responsive design?

**Comment by Bastiti** [comment]
We could add table a class then managing with classes directly

**Comment by Bastiti** [comment]
=> table tag are not hardcoded anymore.

**Pull request closed without merging**
